import {assignExperimentArm,type ExperimentDefinition,type LearningOutcome} from "./experiments.ts";
export type ExperimentEnrollment={experimentId:string;armId:string;unitId:string;assignedAt:string;definitionVersion:string};
export type PendingProbe={experimentId:string;armId:string;conceptId:string;eligibleAfter:string;baselineMastery:number;createdAt:string};
export type ResearchLedger={enrollments:ExperimentEnrollment[];pending:PendingProbe[];outcomes:LearningOutcome[]};
export const emptyResearchLedger=():ResearchLedger=>({enrollments:[],pending:[],outcomes:[]});

/** Enrollment is deterministic and idempotent. definitionVersion must change when treatment behavior changes. */
export function enroll(ledger:ResearchLedger,definition:ExperimentDefinition,definitionVersion:string,unitId:string,at=new Date()):ResearchLedger{const existing=ledger.enrollments.find(e=>e.experimentId===definition.id&&e.unitId===unitId&&e.definitionVersion===definitionVersion);if(existing)return ledger;const enrollment={experimentId:definition.id,armId:assignExperimentArm(definition,unitId),unitId,assignedAt:at.toISOString(),definitionVersion};return {...ledger,enrollments:[...ledger.enrollments,enrollment]}}
export function scheduleProbe(ledger:ResearchLedger,probe:PendingProbe):ResearchLedger{const duplicate=ledger.pending.some(p=>p.experimentId===probe.experimentId&&p.conceptId===probe.conceptId&&p.createdAt===probe.createdAt);return duplicate?ledger:{...ledger,pending:[...ledger.pending,probe]}}
export function resolveProbe(ledger:ResearchLedger,experimentId:string,conceptId:string,outcome:LearningOutcome,at=new Date()):ResearchLedger{const probe=ledger.pending.find(p=>p.experimentId===experimentId&&p.conceptId===conceptId&&new Date(p.eligibleAfter)<=at);if(!probe)throw new Error("No eligible delayed probe");if(probe.armId!==outcome.armId)throw new Error("Outcome arm does not match enrollment");return {...ledger,pending:ledger.pending.filter(p=>p!==probe),outcomes:[...ledger.outcomes,outcome]}}
export function validateLedger(ledger:ResearchLedger){const errors:string[]=[];for(const outcome of ledger.outcomes){if(!(outcome.retention>=0&&outcome.retention<=1))errors.push("Retention outside [0,1]");if(!(outcome.accuracy>=0&&outcome.accuracy<=1))errors.push("Accuracy outside [0,1]");if(outcome.meanSolveTimeMs<0)errors.push("Negative solve time")}return {valid:errors.length===0,errors}}
