import type {Domain} from "./types.ts";
export type Concept={id:string;domain:Domain;area:string;name:string;prerequisites:string[];difficulty:number;frequency:number};
const m=(id:string,area:string,name:string,prerequisites:string[]=[],difficulty=1,frequency=.5):Concept=>({id,domain:"Math",area,name,prerequisites,difficulty,frequency});
const r=(id:string,area:string,name:string,prerequisites:string[]=[],difficulty=1,frequency=.5):Concept=>({id,domain:"Reading & Writing",area,name,prerequisites,difficulty,frequency});
export const concepts:Concept[]=[
 m("linear-equations","Algebra","Linear equations",[],1,.9),m("linear-functions","Algebra","Linear functions",["linear-equations"],2,.9),m("systems","Algebra","Systems of equations",["linear-equations"],2,.75),m("inequalities","Algebra","Linear inequalities",["linear-equations"],2,.65),m("slope","Algebra","Slope and rate of change",["linear-equations"],2,.8),m("equivalent-expressions","Algebra","Equivalent expressions",[],1,.7),
 m("exponents","Advanced Math","Exponent rules",[],1,.6),m("radicals","Advanced Math","Radical expressions",["exponents"],2,.5),m("polynomials","Advanced Math","Polynomial operations",["exponents"],2,.65),m("factoring","Advanced Math","Factoring",["polynomials"],2,.7),m("quadratics","Advanced Math","Quadratic equations",["factoring"],3,.85),m("quadratic-forms","Advanced Math","Quadratic forms",["quadratics"],3,.65),m("nonlinear-functions","Advanced Math","Nonlinear functions",["linear-functions"],3,.6),m("rational-expressions","Advanced Math","Rational expressions",["polynomials"],3,.45),m("function-notation","Advanced Math","Function notation",["linear-functions"],2,.65),
 m("ratios","Problem Solving & Data Analysis","Ratios and proportions",[],1,.7),m("percent","Problem Solving & Data Analysis","Percent",["ratios"],1,.75),m("units","Problem Solving & Data Analysis","Units and rates",["ratios"],2,.55),m("scatterplots","Problem Solving & Data Analysis","Scatterplots",[],1,.55),m("statistics-center","Problem Solving & Data Analysis","Center and spread",[],2,.65),m("probability","Problem Solving & Data Analysis","Probability",["ratios"],2,.55),m("conditional-probability","Problem Solving & Data Analysis","Conditional probability",["probability"],3,.35),m("sampling","Problem Solving & Data Analysis","Sampling and inference",["statistics-center"],3,.5),
 m("angles","Geometry & Trigonometry","Angles and lines",[],1,.5),m("triangles","Geometry & Trigonometry","Triangle geometry",["angles"],2,.7),m("similarity","Geometry & Trigonometry","Similarity",["triangles","ratios"],2,.6),m("right-triangles","Geometry & Trigonometry","Right triangles",["triangles"],2,.65),m("trigonometry","Geometry & Trigonometry","Trigonometry",["right-triangles"],3,.55),m("circles","Geometry & Trigonometry","Circles",["angles"],2,.65),m("area-volume","Geometry & Trigonometry","Area and volume",[],2,.6),m("coordinate-geometry","Geometry & Trigonometry","Coordinate geometry",["linear-equations"],2,.55),
 r("central-ideas","Information & Ideas","Central ideas and details",[],1,.9),r("evidence","Information & Ideas","Command of evidence",["central-ideas"],2,.9),r("inferences","Information & Ideas","Inferences",["central-ideas"],2,.85),r("data-evidence","Information & Ideas","Quantitative evidence",["evidence"],2,.55),
 r("words-context","Craft & Structure","Words in context",[],2,.9),r("text-purpose","Craft & Structure","Text structure and purpose",["central-ideas"],2,.75),r("cross-text","Craft & Structure","Cross-text connections",["inferences"],3,.55),
 r("transitions","Expression of Ideas","Transitions",[],1,.8),r("rhetorical-synthesis","Expression of Ideas","Rhetorical synthesis",["central-ideas"],2,.8),
 r("boundaries","Standard English Conventions","Sentence boundaries",[],1,.9),r("form-structure-sense","Standard English Conventions","Form, structure, and sense",["boundaries"],2,.9),r("agreement","Standard English Conventions","Subject-verb agreement",["form-structure-sense"],2,.65),r("pronouns","Standard English Conventions","Pronouns",["form-structure-sense"],2,.55),r("modifiers","Standard English Conventions","Modifiers",["form-structure-sense"],2,.55),r("verb-tense","Standard English Conventions","Verb tense and form",["form-structure-sense"],2,.6),r("punctuation","Standard English Conventions","Punctuation",["boundaries"],2,.8)
];
export const conceptById=new Map(concepts.map(c=>[c.id,c]));
export const domains=["Math","Reading & Writing"] as const;
